### ISSUE TITLE
fsockopen() - Verbindungsaufbau abgelehnt

### ISSUE THREAD

**Issue by chbardel** [matthanley/smarter-coffee-api#1]
I get the following error:`Warning:  fsockopen(): unable to connect to 192.168.8.178:2081 (Verbindungsaufbau abgelehnt)`

Can you check if it is still working? Maybe there was an firmware update recently. IP address is correct. Double checked that.

**Comment by matthanley** [comment]
Unfortunately I don't have easy access to a Smarter machine any more. You could try port scanning the machine with `nmap` to check the port is correct. The API was originally reverse-engineered using Wireshark to capture actions from the app so you could also give that a try.
